# Site settings
title: ncvreg
email: patrick-breheny@uiowa.edu
description: "ncvreg: Regularization paths for SCAD- and MCP-penalized regression models"
github_username: pbreheny

# Build settings
markdown: kramdown
exclude: [Makefile, src, cache, README.md]
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
